var resources = 
{
     Subscription:
        [
            {
                property:'id',
                indexedProperty:'_id',
                type:'string',
                global:'id'
            },
            {
                property:'lastUpdated',
                indexedProperty:'_lastUpdated',
                type:'datetime',
                global:'datetime'
            },
            {
                property:'tag',
                indexedProperty:'_tag',
                type:'token',
                global:'token'
            }, 
            {
                property:'status',
                type:'string',
                global:'string'
            },
            {
                property:'payload',
                type:'string',
                global:'string'
            },
            {
                property:'type',
                type:'string',
                global:'string'
            },
            {
                property:'endpoint',
                indexedProperty:'url',
                type:'uri',
                global:'uri'
            }
        ],
     Patient:
        [
            {
                property:"id",
                indexedProperty:"_id",
                type:"string",
                global:"id"
            },
            {
                property:"lastUpdated",
                indexedProperty:"_lastUpdated",
                type:"datetime",
                global:"datetime"
            },
            {
                property:"city",
                indexedProperty:"address-city",
                type:"string",
                global:"string"
            },
            {
                property:"district",
                indexedProperty:"address-state",
                type:"string",
                global:"string"
            },
            {
                property:"postalCode",
                indexedProperty:"address-postalcode",
                type:"string",
                global:"string"
            },
            {
                property:"name",
                type:"name",
                global:"name"
            },        
            {
                property:"identifier",
                indexedProperty:"identifier",
                type:"token",
                global:"token"
            },
            {
                property:"tag",
                indexedProperty:"_tag",
                type:"token",
                global:"token"
            },
            {
                property:"gender",
                type:"string",
                global:"string"
            },
            {
                property:"birthDate",
                type:"datetime",
                global:"datetime"
            },
            {
                property:"managingOrganization",
                type:"reference",
                global:"reference"
            },
            {
                property:"generalPractitioner",
                type:"reference",
                global:"reference"
            }
        ],
     Encounter: 
     [
        {
            property:"id",
            indexedProperty:"_id",
            type:"string",
            global:"id"
        },
        {
            property:"lastUpdated",
            indexedProperty:"_lastUpdated",
            type:"datetime",
            global:"datetime"
        },
        {
            property:"tag",
            indexedProperty:"_tag",
            type:"token",
            global:"token"
        },
        {
            property:"class",
            indexedProperty:"class",
            type:"token",
            global:"token"
        },
        {
            property:"condition",
            indexedProperty:"diagnosis",
            type:"reference",
            global:"reference"
        },
        {
            property:"episodeOfCare",
            indexedProperty:"episode-of-care",
            type:"reference",
            global:"reference"
        },
        {
            property:"identifier",
            indexedProperty:"identifier",
            type:"token",
            global:"token"
        },
        {
            property:"location",
            indexedProperty:"location",
            type:"reference",
            global:"reference"
        },
        {
            //This form allows complext types to be "split" into separate globals... participant-type is a codeableConcept/token (type) and participant is a reference (individual)
            //The participant index handler knows where to pick out the codeable concept and reference from the participant object.
            property:"participant",
            indexedProperty:["participant-type","participant"],
            type:"participant",
            global:["token","reference"],
            indexPropertyGlobals:{
                "participant-type":"token",
                "participant":"reference"
            }
        },
        {
            property:"partOf",
            indexedProperty:"part-of",
            type:"reference",
            global:"reference"
        },
        {
            property:"period",
            indexedProperty:"date",
            type:"period",
            global:"period"
        },
        {
            property:"type",
            indexedProperty:"type",
            type:"codeableConcept",
            global:"token",
            allowMultiple:false
        },
        {
            property:"subject",
            indexedProperty:"patient",
            type:"reference",
            global:"reference"
        },
        {
            property:"status",
            type:"string",
            global:"string",
            allowMultiple:false
        }
    ]
}

module.exports = {
    resources
};